export const LOGIN_STATUS_RESPONSE_CODE = {
  WAIT_2000MS_COUNT: -1,
  EXCHANGE_KEYS: 0,
  WAIT_2000MS: 1,
  SUCCESS: 2,
  INVALID_USERNAME_PASSWORD: 3,
  LOGIN_REJECT_SESSION: 11,
  INVALID_CREDENTIALS_COMBINATION: 28,
  // ... and more
};
